server:
  port: 8080

spring:
  application:
    name: user-management-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql-user:5432/academix_users_db}
    username: ${SPRING_DATASOURCE_USERNAME:academix_user}
    password: ${SPRING_DATASOURCE_PASSWORD:academix_password}
    driver-class-name: org.postgresql.Driver
  # JPA (Hibernate) configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}
  instance:
    hostname: user-management-service
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.springframework.cloud.netflix: DEBUG
    com.academix: DEBUG
