server:
  port: 8080

spring:
  application:
    name: user-management-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:lms_user}
    password: ${SPRING_DATASOURCE_PASSWORD:lms_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'none' or 'validate' in production and rely on Flyway/Liquibase.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # For Spring Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/lms # Example for Keycloak, will use custom later
          jwk-set-uri: http://localhost:8080/realms/lms/protocol/openid-connect/certs # Example for Keycloak

# Spring Boot Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.academix: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG # Show SQL queries from Hibernate
    org.hibernate.orm.jdbc.bind: TRACE # Show SQL parameter bindings