[ req ]
default_bits = 2048
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[ req_distinguished_name ]
CN = consul-server

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = consul-server
DNS.2 = localhost
DNS.3 = 127.0.0.1
DNS.4 = host.docker.internal
DNS.5 = server.dc1.consul
DNS.6 = server-1
DNS.7 = server-1.node.dc1.consul
DNS.8 = consul-server
DNS.9 = api-gateway
DNS.10 = user-management-service
DNS.11 = course-management-service
DNS.12 = academix-course-db
DNS.13 = academix-user-db
IP.1 = 127.0.0.1
IP.2 = 172.18.0.2  # consul-server
IP.3 = 172.18.0.3  # academix-course-db
IP.4 = 172.18.0.4  # academix-user-db
IP.5 = 172.18.0.5  # Will be api-gateway
IP.6 = 172.18.0.6  # Will be user-management-service
IP.7 = 172.18.0.7  # Will be course-management-service
